database:
  dbname: "myapp"
  user: "root"
  password: "password"
  location: "127.0.0.1"
  port: "3306"
  logPath: "/Users/vinodborole/Documents/personal/projects/poc/gormv2-poc/log/gorm.log"
application:
  http-port: "8080"
  name: "gormv2-poc"
  description: "Gorm version 2 POC"
log:
  location: "/Users/vinodborole/Documents/personal/projects/poc/gormv2-poc/log/"
  # error, warning, info, debug
  level: "info"
  maxbackups: 250
  maxage: 60   #days